# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Survey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReactorKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'

  target 'SurveyTests' do
    pod 'RxBlocking'
    inherit! :search_paths
  end

  target 'SurveyUITests' do
    # Pods for testing
  end

end
